### ISSUE TITLE
JavaScript error in "AdGuard Extra.user.js" in older browsers versions

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardExtra#4]
@victor-homyakov commented on [Wed Jun 19 2019](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1431)

### Steps to reproduce
1. Install older version of Chrome (53 and older) or Opera (40 and older)
2. Install AdGuard with AdGuard Extra script
3. Open yandex.ru

### Expected behavior
No errors should happen

### Actual behavior
Older browsers (Opera 40 and older, Chrome 53 and older) will throw JavaScript error

```
TypeError: Object.values is not a function
    at findAds (AdGuard%20Extra.user.js:71:7335)
    at hideYaDirectAds (AdGuard%20Extra.user.js:71:7938)
    at MutationObserver.eval (AdGuard%20Extra.user.js:71:8766)
```

because JavaScript in `AdGuard Extra.user.js` uses `Object.values()`, which isn't supported in older browser versions https://caniuse.com/#search=Object.values.

### Your environment
* AdGuard AdBlocker extension version: 
* Environment name and version: Chrome/53.0.2785.21
* Filters you use in AdGuard:
* Any other browser extensions you have installed: none

**Comment by victor-homyakov** [comment]
Also script https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js contains the same function repeated five times with different names:

```js
    function d(e) {
        return function(e) {
            if (Array.isArray(e)) {
                for (var t = 0, n = new Array(e.length); t < e.length; t++) n[t] = e[t];
                return n
            }
        }(e) || function(e) {
            if (Symbol.iterator in Object(e) || "[object Arguments]" === Object.prototype.toString.call(e)) return Array.from(e)
        }(e) || function() {
            throw new TypeError("Invalid attempt to spread non-iterable instance")
        }()
    }

...

    function g(e) {
        return function(e) {
            if (Array.isArray(e)) {
                for (var t = 0, n = new Array(e.length); t < e.length; t++) n[t] = e[t];
                return n
            }
        }(e) || function(e) {
            if (Symbol.iterator in Object(e) || "[object Arguments]" === Object.prototype.toString.call(e)) return Array.from(e)
        }(e) || function() {
            throw new TypeError("Invalid attempt to spread non-iterable instance")
        }()
    }

...

    function m(e) {
        return function(e) {
            if (Array.isArray(e)) {
                for (var t = 0, n = new Array(e.length); t < e.length; t++) n[t] = e[t];
                return n
            }
        }(e) || function(e) {
            if (Symbol.iterator in Object(e) || "[object Arguments]" === Object.prototype.toString.call(e)) return Array.from(e)
        }(e) || function() {
            throw new TypeError("Invalid attempt to spread non-iterable instance")
        }()
    }

...

    function w(e) {
        return function(e) {
            if (Array.isArray(e)) {
                for (var t = 0, n = new Array(e.length); t < e.length; t++) n[t] = e[t];
                return n
            }
        }(e) || function(e) {
            if (Symbol.iterator in Object(e) || "[object Arguments]" === Object.prototype.toString.call(e)) return Array.from(e)
        }(e) || function() {
            throw new TypeError("Invalid attempt to spread non-iterable instance")
        }()
    }

    function S(e) {
        return function(e) {
            if (Array.isArray(e)) {
                for (var t = 0, n = new Array(e.length); t < e.length; t++) n[t] = e[t];
                return n
            }
        }(e) || function(e) {
            if (Symbol.iterator in Object(e) || "[object Arguments]" === Object.prototype.toString.call(e)) return Array.from(e)
        }(e) || function() {
            throw new TypeError("Invalid attempt to spread non-iterable instance")
        }()
    }
```

Looks like a new function is inserted for each transpiled spread operator. In any case there is an opportunity for improvement.

**Comment by ameshkov** [comment]
Yeah, we don't use plugin-transform-runtime as it tends to pollute global scope even when corejs 3 is enabled. Anyways, we can improve the build process to avoid duplications, thanks for reporting it!
